version = 1

# .NET Core Analysis
[[analyzers]]
name = "csharp"
enabled = true

# Frontend Analysis (if using Angular/React)
[[analyzers]]
name = "typescript"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

# Infrastructure Analysis
[[analyzers]]
name = "dockerfile"
enabled = true

[[analyzers]]
name = "yaml"
enabled = true

# Security Analysis
[[analyzers]]
name = "secrets"
enabled = true

# Test Configuration
[[tests]]
name = "dotnet-test"
enabled = true
path = "tests/"
command = "dotnet test --collect:\"XPlat Code Coverage\""

# Coverage Settings
[coverage]
min_coverage = 80
max_missing = 15

# Build Configuration
[build]
command = "dotnet build"
environment = { DOTNET_CLI_TELEMETRY_OPTOUT = "1" }

# Dependency Scanning
[dependency_scanning]
enabled = true
package_managers = ["nuget", "npm"]

# Exclusions
exclude = [
  # .NET
  "bin/",
  "obj/",
  "packages/",
  "Migrations/",
  
  # Frontend
  "node_modules/",
  "dist/",
  "*.min.js",
  "*.min.css",
  
  # General
  ".git/",
  ".github/",
  ".vscode/"
]

# Custom ignores
[[ignore]]
pattern = ".*TODO.*"
reason = "Development note"

[[ignore]]
pattern = ".*Debug\\.Assert\\(.*"
reason = "Debugging statements"
