version = 1

# Valid analyzers for .NET Core
[[analyzers]]
name = "csharp"
enabled = true

# Test configuration for xUnit/NUnit/MSTest
[[tests]]
name = "dotnet-test"
enabled = true
path = "tests/"
command = "dotnet test --collect:\"XPlat Code Coverage\""

# Code coverage settings
[coverage]
min_coverage = 80
max_missing = 15

# Exclude common .NET directories
exclude = [
  "bin/",
  "obj/",
  "packages/",
  "wwwroot/",
  "*.min.js",
  "*.min.css",
  "appsettings.Development.json",
  "Migrations/"
]

# Custom ignore patterns for .NET
[[ignore]]
pattern = ".*TODO.*"
reason = "Development note"

[[ignore]]
pattern = ".*Debug\\.Assert\\(.*"
reason = "Debugging statements"

# Build configuration
[build]
command = "dotnet build"
environment = { DOTNET_CLI_TELEMETRY_OPTOUT = "1" }

# Dependency scanning (uses csharp analyzer for NuGet)
[dependency_scanning]
enabled = true
package_managers = ["nuget"]
