version = 1

[[analyzers]]
name = "csharp"
enabled = true

# Add CSS-specific analysis
[[analyzers]]
name = "css"
enabled = true
args = ["--stylelint-config=standard"]

# HTML analysis
[[analyzers]]
name = "html"
enabled = true

# Test configuration
[[tests]]
name = "dotnet-test"
enabled = true
path = "tests/"
command = "dotnet test --collect:\"XPlat Code Coverage\""

# Explicitly include all web assets
include = [
  "**/*.css",
  "**/*.html",
  "**/*.cshtml",
  "**/*.scss",
  "**/*.js"
]

# Smarter exclusions
exclude = [
  "bin/",
  "obj/",
  "packages/",
  "node_modules/",
  "*.min.*"  # Excludes all minified files
]

[build]
command = "dotnet build"
