version = 1

[[analyzers]]
name = "csharp"  # Only officially supported .NET analyzer
enabled = true

[[tests]]
name = "dotnet-test"
enabled = true
path = "tests/"
command = "dotnet test"

exclude = [
  "bin/", "obj/", "packages/",
  "node_modules/", "*.min.*"
]
