version = 1

# Only supported analyzers for .NET
[[analyzers]]
name = "csharp"
enabled = true

# Test configuration
[[tests]]
name = "dotnet-test"
enabled = true
path = "tests/"
command = "dotnet test --collect:\"XPlat Code Coverage\""

# Code coverage settings
[coverage]
min_coverage = 80
max_missing = 15

# Dependency scanning (NuGet only)
[dependency_scanning]
enabled = true
package_managers = ["nuget"]

# Exclusions
exclude = [
  "bin/",
  "obj/",
  "packages/",
  "wwwroot/",
  "Migrations/",
  "node_modules/",
  "*.min.js",
  "*.min.css",
  "appsettings.Development.json"
]

# Custom ignore patterns
[[ignore]]
pattern = ".*TODO.*"
reason = "Development note"

[[ignore]]
pattern = ".*Debug\\.Assert\\(.*"
reason = "Debugging statements"

# Build configuration
[build]
command = "dotnet build"
environment = { DOTNET_CLI_TELEMETRY_OPTOUT = "1" }
