version = 1

[[analyzers]]
name = "csharp"
enabled = true

# Test configuration
[[tests]]
name = "dotnet-test"
enabled = true
path = "tests/"
command = "dotnet test --collect:\"XPlat Code Coverage\""

# Code coverage
[coverage]
min_coverage = 80
max_missing = 15

# Dependency scanning
[dependency_scanning]
enabled = true
package_managers = ["nuget"]

# Smart exclusions - keeping files you want analyzed
exclude = [
  # Build outputs (keep these excluded)
  "bin/",
  "obj/",
  "packages/",
  
  # Node dependencies (keep excluded)
  "node_modules/",
  
  # Minified files (keep excluded as they're generated)
  "*.min.js",
  "*.min.css",
  
  # Development configs (keep excluded)
  "appsettings.Development.json"
]

# Explicitly include these patterns for analysis
include = [
  "**/*.css",
  "**/*.html", 
  "**/*.cshtml",
  "**/*.razor",
  "**/*.js",
  "**/*.ts"
]

# Custom ignores
[[ignore]]
pattern = ".*TODO.*"
reason = "Development note"

[build]
command = "dotnet build"
