version = 1

[[analyzers]]
name = "csharp"
enabled = true

[[tests]]
name = "dotnet-test"
enabled = true
path = "tests/"
command = "dotnet test --collect:\"XPlat Code Coverage\""

[coverage]
min_coverage = 80

[dependency_scanning]
enabled = true
package_managers = ["nuget"]

exclude = [
  "bin/",
  "obj/",
  "packages/",
  "node_modules/",
  "*.min.js",
  "*.min.css"
]
