name: Deploy to Dev

on:
  workflow_run:
    workflows: [".NET"]  # Must match EXACTLY the name in `dotnet.yml`
    branches: [master]
    types:
      - completed

jobs:
  deploy-to-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the `dev` branch (with full history)
      - name: Checkout Dev Branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0  # Required for merging

      # 2. Download artifacts from the CI workflow (using v4)
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./artifacts/

      # 3. Merge `master` into `dev` (only if needed)
      - name: Merge Changes from Master
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin master
          git merge origin/master --no-edit --no-ff

      # 4. Copy artifacts and commit changes (if any)
      - name: Update Dev Branch with Artifacts
        run: |
          # Copy artifacts to the root (or desired location)
          cp -r ./artifacts/* ./ || echo "No new artifacts"
          
          # Check for changes before committing
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update from master (Run: ${{ github.run_id }})"
            git push origin dev
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
