name: Deploy to Dev

on:
  workflow_run:
    workflows: [".NET CI"]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # Get the workflow run ID from the triggering event
      - name: Get Workflow Run ID
        id: get_run_id
        run: echo "run_id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
        
      # Download artifacts from the SPECIFIC workflow run
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/
          run-id: ${{ steps.get_run_id.outputs.run_id }}  # Critical fix!
          
      # Checkout dev branch
      - name: Checkout Dev
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          
      # Update dev branch
      - name: Update Dev Branch
        run: |
          # Copy artifacts
          cp -r artifacts/* .
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update from master (Run ${{ github.event.workflow_run.id }})"
            git push origin dev
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
