name: Deploy to Dev

on:
  workflow_run:
    workflows: [".NET CI"]
    branches: [master]
    types:
      - completed

jobs:
  deploy-to-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/
          workflow_run: ${{ github.event.workflow_run.id }}  # Critical fix!
          
      - name: Checkout Dev Branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          
      - name: Merge and Update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Copy artifacts
          cp -r artifacts/* . || echo "No new artifacts"
          
          # Commit changes
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update from master build ${{ github.event.workflow_run.id }}"
            git push origin dev
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
