name: Build and Deploy

on:
  push:
    branches: [master]

permissions:  # 👈 Add this section
  contents: write  # Required to push to branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Build
        run: dotnet build --configuration Release
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: bin/Release/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # 👈 Add this
          
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .
          
      - name: Update Dev Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update from master (Run ${{ github.run_number }})"
            git push origin dev
          fi
